# -*- coding: utf-8 -*-
"""jogo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmcNY7YujJJe30YqbxrjYhrdr0e3qoeZ
"""

import numbers
import words

print("*********************************")
print('========Chosse the game!=======')
print("*********************************")

print('(1) SPELLING WORDS   (2) NUMBERS')
game = int(input('Which game? '))

if game ==1:
  print('Spelling Words game!')
  words.play()
elif game ==2:
  print('Numbers game!')
  numbers.play()